x-vllm-full-cache-volumes: &vllm_full_cache_volumes
  - ./chat-templates/:/app/chat-templates
  - ${HOME}/.cache/huggingface:/root/.cache/huggingface
  - ${HOME}/.cache/vllm:/root/.cache/vllm
  - ${HOME}/.cache/triton:/root/.cache/triton
  - ${HOME}/.cache/torchinductor:/root/.cache/torchinductor
  - ${HOME}/.cache/aiter:/root/.aiter
  - ${HOME}/.cache/comgr:/root/.cache/comgr
  - ${HOME}/.cache/tvm-ffi:/root/.cache/tvm-ffi

x-amd-devices: &amd_devices
  devices:
    - /dev/kfd:/dev/kfd
    - /dev/dri:/dev/dri
  group_add:
    - "video"
  cap_add:
    - SYS_PTRACE
  security_opt:
    - label=disable
  ipc: host

services:
  vllm:
    <<: *amd_devices
    image: localhost/vllm-fullbuild:latest
    build:
      context: .
      dockerfile: Dockerfile.fullbuild
      args:
        ROCM_IMAGE: ${ROCM_IMAGE}
        GPU_ARCH: ${GPU_ARCH}
        MAX_JOBS: ${MAX_JOBS}
        TORCH_VERSION: ${TORCH_VERSION}
        TORCHVISION_VERSION: ${TORCHVISION_VERSION}
        TORCHAUDIO_VERSION: ${TORCHAUDIO_VERSION}
        VLLM_REF: ${VLLM_REF}
        VLLM_VERSION: ${VLLM_VERSION}
        AITER_REF: ${AITER_REF}
        FLASH_ATTN_REF: ${FLASH_ATTN_REF}
    container_name: vllm
    restart: unless-stopped
    ports:
      - "8180:8180"
    networks:
      default:
        aliases:
          - llm-backend
    volumes: *vllm_full_cache_volumes
    env_file:
      - env/2xr9700.vllm.common
      - env/aiter-unified-attention.env
    environment:
      - GPU_MAX_HW_QUEUES=1
      - NCCL_P2P_DISABLE=1
    command: >
      ${VLLM_MODEL}
      --tokenizer ${VLLM_TOKENIZER}
      --served-model-name ${VLLM_SERVED_NAME}
      --limit-mm-per-prompt '{"image": 99, "audio": 0, "video": 0}'
      ${VLLM_TOOL_CHOICE}
      --max-model-len 131072
      --max-num-batched-tokens ${VLLMM_MAX_BATCHED_TOKENS:-8192}
      --enable-prefix-caching
      --override-generation-config '{"temperature": 1.0, "top_p": 0.95, "top_k": 20, "min_p": 0.0, "presence_penalty": 0.0, "repetition_penalty": 1.0}'
      --gpu-memory-utilization 0.8
      --host 0.0.0.0
      --port 8180
      --dtype auto
      --max-num-seqs 1
      --kv-cache-dtype ${VLLM_KV_CACHE_DTYPE:-fp8}
      -tp 2
      --attention-backend ROCM_AITER_UNIFIED_ATTN
      --speculative-config '${VLLM_SPEC_DECODE}'
